import { PrismaClient } from "@prisma/client";
import bcrypt from "bcrypt";

const prisma = new PrismaClient();

// Default admin password (change after first login). Document in .env.example.
const ADMIN_DEFAULT_PASSWORD = process.env.ADMIN_DEFAULT_PASSWORD ?? "KosherConnect2025!";

function slug(name: string, city: string): string {
  return (name + " " + city).toLowerCase().replace(/[^\w\s-]/g, "").replace(/[\s_]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 80);
}

async function main() {
  console.log("🕎 Seeding Kosher Connect — FULL 4-CITY DATABASE\n");

  // Categories
  const cats = [
    { name: "Shabbat", slug: "shabbat", icon: "🕯️" },
    { name: "Simcha", slug: "simcha", icon: "🎉" },
    { name: "Wedding", slug: "wedding", icon: "💍" },
    { name: "Bar Mitzvah", slug: "bar-mitzvah", icon: "📜" },
    { name: "Food", slug: "food", icon: "🍽" },
    { name: "Workshop", slug: "workshop", icon: "🎓" },
    { name: "Holiday", slug: "holiday", icon: "✡️" },
    { name: "Community", slug: "community", icon: "🤝" },
    { name: "Dairy", slug: "dairy", icon: "🧀" },
    { name: "Meat", slug: "meat", icon: "🥩" },
    { name: "Pareve", slug: "pareve", icon: "🥗" },
  ];
  for (const c of cats) await prisma.category.upsert({ where: { slug: c.slug }, update: {}, create: c });
  console.log(`✓ ${cats.length} categories`);

  const adminPasswordHash = await bcrypt.hash(ADMIN_DEFAULT_PASSWORD, 10);
  const admin = await prisma.user.upsert({
    where: { email: "admin@kosherconnect.app" },
    update: { passwordHash: adminPasswordHash },
    create: {
      name: "KC Admin",
      email: "admin@kosherconnect.app",
      passwordHash: adminPasswordHash,
      role: "SUPER_ADMIN",
      plan: "FAMILY",
    },
  });

  const listings: any[] = [
  {
    "name": "Angel Bakery and Cafe",
    "type": "BAKERY",
    "address": "17928 Ventura Blvd",
    "city": "Encino",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "818-881-1100",
    "pasYisroel": true
  },
  {
    "name": "Classic Pastry",
    "type": "BAKERY",
    "address": "8670 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-659-4966",
    "pasYisroel": true,
    "yoshon": true
  },
  {
    "name": "Continental Kosher Bakery",
    "type": "BAKERY",
    "address": "12419 Burbank Blvd",
    "city": "Valley Village",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "818-762-5005",
    "pasYisroel": true,
    "yoshon": true
  },
  {
    "name": "Eilat Bakery Caf\u00e9",
    "type": "BAKERY",
    "address": "9060 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "pasYisroel": true,
    "cholovYisroel": true
  },
  {
    "name": "Erin McKenna's Bakery",
    "type": "BAKERY",
    "address": "236 N. Larchmont Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "323-463-2023",
    "website": "https://www.erinmckennasbakery.com"
  },
  {
    "name": "Got Kosher Bakery",
    "type": "BAKERY",
    "address": "8758 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-858-3123",
    "pasYisroel": true
  },
  {
    "name": "Renaissance Bakery",
    "type": "BAKERY",
    "address": "14540 Friar St",
    "city": "Van Nuys",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "818-778-6230",
    "pasYisroel": true,
    "yoshon": true
  },
  {
    "name": "Unique Bakery",
    "type": "BAKERY",
    "address": "18385 Ventura Blvd",
    "city": "Tarzana",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "818-757-3100",
    "pasYisroel": true,
    "yoshon": true
  },
  {
    "name": "Magnolia Bakery",
    "type": "BAKERY",
    "address": "8389 W. Third St",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-309-0316"
  },
  {
    "name": "Schwartz Bakery",
    "type": "BAKERY",
    "address": "8856 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "O/K",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-777-7577",
    "yoshon": true,
    "rating": 4.8,
    "reviewCount": 623
  },
  {
    "name": "Nothing Bundt Cakes Glendale",
    "type": "BAKERY",
    "address": "215 N Glendale Ave",
    "city": "Glendale",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "Nothing Bundt Cakes Sherman Oaks",
    "type": "BAKERY",
    "address": "14622 Ventura Blvd",
    "city": "Sherman Oaks",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "Nothing Bundt Cakes West Hills",
    "type": "BAKERY",
    "address": "6524 Platt Ave",
    "city": "West Hills",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "Fred's Bakery",
    "type": "BAKERY",
    "address": "2831 S. Robertson Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher LA",
    "kosherStatus": true,
    "status": "ACTIVE",
    "pasYisroel": true
  },
  {
    "name": "Sweet E's Bakeshop",
    "type": "BAKERY",
    "address": "4574 W Adams Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher LA",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "Beverly Hills Kosher Meats",
    "type": "BUTCHER",
    "address": "9213 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-278-6347"
  },
  {
    "name": "Cambridge Farms",
    "type": "GROCERY",
    "address": "12341 Burbank Blvd",
    "city": "North Hollywood",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "818-506-6661"
  },
  {
    "name": "Elite Fresh Fish",
    "type": "GROCERY",
    "address": "8730 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-659-9253"
  },
  {
    "name": "Everfresh Kosher Market",
    "type": "GROCERY",
    "address": "17977 Ventura Blvd",
    "city": "Encino",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "818-343-7900"
  },
  {
    "name": "Fish In the Village",
    "type": "GROCERY",
    "address": "12451 Burbank Blvd #B",
    "city": "Valley Village",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "818-769-0085"
  },
  {
    "name": "Glatt Mart",
    "type": "GROCERY",
    "address": "8708 W Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-289-6888"
  },
  {
    "name": "Le Market",
    "type": "GROCERY",
    "address": "12516 Burbank Blvd",
    "city": "Valley Village",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "818-763-5223"
  },
  {
    "name": "Livonia Glatt Market",
    "type": "GROCERY",
    "address": "8922 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-271-4343"
  },
  {
    "name": "Mega Glatt Mart",
    "type": "GROCERY",
    "address": "6114 Reseda Blvd",
    "city": "Tarzana",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "818-578-5856"
  },
  {
    "name": "Super Sal Market",
    "type": "GROCERY",
    "address": "17630 Ventura Blvd",
    "city": "Encino",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "818-906-2815"
  },
  {
    "name": "Ventura Kosher Meats",
    "type": "BUTCHER",
    "address": "18357 Ventura Blvd",
    "city": "Tarzana",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "818-881-3777"
  },
  {
    "name": "Yoram's Meat",
    "type": "BUTCHER",
    "address": "8730 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-877-4691"
  },
  {
    "name": "Big Market",
    "type": "GROCERY",
    "address": "6003 Fallbrook Ave",
    "city": "Woodland Hills",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "Ralphs Kosher Sherman Oaks",
    "type": "GROCERY",
    "address": "14049 Ventura Blvd",
    "city": "Sherman Oaks",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "747-233-6100"
  },
  {
    "name": "Ralphs Kosher La Brea",
    "type": "GROCERY",
    "address": "260 S La Brea Ave",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "Western Kosher",
    "type": "GROCERY",
    "address": "441 N. Fairfax Ave",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "323-651-1928",
    "rating": 4.3
  },
  {
    "name": "The Bagel Factory Cadillac",
    "type": "BAKERY",
    "address": "8986 Cadillac Ave",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher LA",
    "kosherStatus": true,
    "status": "ACTIVE",
    "pasYisroel": true
  },
  {
    "name": "The Bagel Factory West LA",
    "type": "BAKERY",
    "address": "3004 S. Sepulveda Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher LA",
    "kosherStatus": true,
    "status": "ACTIVE",
    "pasYisroel": true
  },
  {
    "name": "Culinary Creations by Chumie",
    "type": "CATERER",
    "address": "11852 Vose St",
    "city": "North Hollywood",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "818-300-5687"
  },
  {
    "name": "Events by Moshe",
    "type": "CATERER",
    "address": "19309 Vanowen St",
    "city": "Reseda",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "818-674-8434"
  },
  {
    "name": "Kosher Hibachi",
    "type": "CATERER",
    "address": "Los Angeles",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "818-308-5069"
  },
  {
    "name": "LA Kosher Grill Catering",
    "type": "CATERER",
    "address": "550 South Hill Street",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "LS Catering",
    "type": "CATERER",
    "address": "8906 West Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-853-4661"
  },
  {
    "name": "Maohr Catering",
    "type": "CATERER",
    "address": "12405 Sylvan St",
    "city": "North Hollywood",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "P.S. Kosher Foods",
    "type": "CATERER",
    "address": "8701 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-772-2518"
  },
  {
    "name": "Platinum Catering",
    "type": "CATERER",
    "address": "241 S. Detroit St",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "Premier Kosher Catering",
    "type": "CATERER",
    "address": "9213 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "323-521-9057"
  },
  {
    "name": "Sharon's Catering",
    "type": "CATERER",
    "address": "7244 Reseda Blvd",
    "city": "Reseda",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "818-344-7472"
  },
  {
    "name": "Simon's Caterers",
    "type": "CATERER",
    "address": "10505 Santa Monica Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-466-6333"
  },
  {
    "name": "Sinai Catering",
    "type": "CATERER",
    "address": "12233 Santa Monica Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-820-0048"
  },
  {
    "name": "The Barbecue King",
    "type": "CATERER",
    "address": "5765 West Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-770-4842"
  },
  {
    "name": "ChillBachi",
    "type": "CATERER",
    "address": "12431 Burbank Blvd",
    "city": "Valley Village",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "Salam-Tak",
    "type": "CATERER",
    "address": "8474 W 3rd St Unit 108",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "Julie's Bakery Catering",
    "type": "CATERER",
    "address": "9030 Owensmouth Ave",
    "city": "Canoga Park",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "213-820-4366"
  },
  {
    "name": "Majestic Glatt Catering",
    "type": "CATERER",
    "address": "18411 Hatteras St",
    "city": "Tarzana",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "Foodheart Catering",
    "type": "CATERER",
    "address": "6075 Reseda Blvd",
    "city": "Tarzana",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "Bazilikum Kosher Catering",
    "type": "CATERER",
    "address": "1062 S Robertson Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "P'ninas Classic Catering",
    "type": "CATERER",
    "address": "5521 Reseda Blvd #106",
    "city": "Tarzana",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "Arais Machane Yehuda",
    "type": "RESTAURANT",
    "address": "19527 Ventura Blvd",
    "city": "Tarzana",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "818-457-4075",
    "description": "Israeli street food"
  },
  {
    "name": "Basbussa",
    "type": "RESTAURANT",
    "address": "8338 W 3rd St",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "323-452-9250",
    "description": "Middle Eastern"
  },
  {
    "name": "Beverly Hills Thai",
    "type": "RESTAURANT",
    "address": "9036 Burton Way",
    "city": "Beverly Hills",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-288-4321",
    "description": "Kosher Thai"
  },
  {
    "name": "Big Daddy's Shawarma",
    "type": "RESTAURANT",
    "address": "12103 Ventura Blvd",
    "city": "Studio City",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "description": "Shawarma"
  },
  {
    "name": "Cohen Restaurant",
    "type": "RESTAURANT",
    "address": "316 E. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "213-742-8888",
    "description": "Chinese-Israeli"
  },
  {
    "name": "Corridor 18",
    "type": "RESTAURANT",
    "address": "8532 W Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "Dr. Sandwich Olympic",
    "type": "RESTAURANT",
    "address": "9113 W. Olympic Blvd",
    "city": "Beverly Hills",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "818-674-8777",
    "description": "Gourmet sandwiches"
  },
  {
    "name": "Dr. Sandwich Beverly",
    "type": "RESTAURANT",
    "address": "7475 Beverly Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "Geshmak",
    "type": "RESTAURANT",
    "address": "7119 Beverly Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "Hatikva Grill Express",
    "type": "RESTAURANT",
    "address": "14054 Burbank Blvd",
    "city": "Sherman Oaks",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "description": "Israeli grill"
  },
  {
    "name": "Hollywood Falafel",
    "type": "RESTAURANT",
    "address": "Burbank and Whitsett",
    "city": "Valley Village",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "888-495-7747",
    "description": "Falafel"
  },
  {
    "name": "Le Sushi",
    "type": "RESTAURANT",
    "address": "12524 Burbank Blvd",
    "city": "North Hollywood",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "818-763-6600",
    "description": "Kosher sushi"
  },
  {
    "name": "Melrose Burgers N Fries",
    "type": "RESTAURANT",
    "address": "7751 Melrose Ave",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "323-424-7131",
    "description": "Burgers"
  },
  {
    "name": "Melrose Burgers Encino",
    "type": "RESTAURANT",
    "address": "17932 Ventura Blvd",
    "city": "Encino",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "Michaels Cafe Bistro",
    "type": "RESTAURANT",
    "address": "412 W. 6th St",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-895-8890"
  },
  {
    "name": "Next Door LA",
    "type": "RESTAURANT",
    "address": "7475 Beverly Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-933-3021"
  },
  {
    "name": "PSY Street Kitchen",
    "type": "RESTAURANT",
    "address": "15030 Ventura Blvd",
    "city": "Sherman Oaks",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "747-264-0591",
    "description": "Korean-Israeli"
  },
  {
    "name": "Shalom Grill",
    "type": "RESTAURANT",
    "address": "9340 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-278-4692",
    "description": "Israeli grill"
  },
  {
    "name": "Tasty Kosher Kitchen",
    "type": "RESTAURANT",
    "address": "19309 Vanowen St",
    "city": "Reseda",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "Tel Aviv Chef Kitchen",
    "type": "RESTAURANT",
    "address": "17630 Ventura Blvd",
    "city": "Encino",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "description": "Authentic Israeli"
  },
  {
    "name": "Tel Aviv Grill Encino",
    "type": "RESTAURANT",
    "address": "17201 Ventura Blvd",
    "city": "Encino",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "Tel Aviv Grill Woodland Hills",
    "type": "RESTAURANT",
    "address": "2734 Mulholland Dr",
    "city": "Woodland Hills",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "Tel Aviv Grill Valley Village",
    "type": "RESTAURANT",
    "address": "12450 Burbank Blvd",
    "city": "Valley Village",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "The Holy Grill Downtown",
    "type": "RESTAURANT",
    "address": "120 E. 15th Street",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE"
  },
  {
    "name": "The Holy Grill Pico",
    "type": "RESTAURANT",
    "address": "8975 W Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-275-4420"
  },
  {
    "name": "TLV Tapas Bar",
    "type": "RESTAURANT",
    "address": "5442 Yolanda Ave",
    "city": "Tarzana",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "818-201-6171",
    "description": "Israeli tapas"
  },
  {
    "name": "Harissa",
    "type": "RESTAURANT",
    "address": "8914 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-858-3123",
    "description": "Moroccan-Israeli"
  },
  {
    "name": "Borekas Sherman Oaks",
    "type": "RESTAURANT",
    "address": "15030 Ventura Blvd Ste 25",
    "city": "Sherman Oaks",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "cholovYisroel": true,
    "phone": "818-688-4588"
  },
  {
    "name": "Borekas Van Nuys",
    "type": "RESTAURANT",
    "address": "5530 Van Nuys Blvd",
    "city": "Van Nuys",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "cholovYisroel": true
  },
  {
    "name": "Borekas Woodland Hills",
    "type": "RESTAURANT",
    "address": "19714 Ventura Blvd",
    "city": "Woodland Hills",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "cholovYisroel": true
  },
  {
    "name": "Brami's Pizza",
    "type": "RESTAURANT",
    "address": "17736 Sherman Way",
    "city": "Reseda",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "cholovYisroel": true,
    "phone": "818-342-0611"
  },
  {
    "name": "Formaggi Pizza",
    "type": "RESTAURANT",
    "address": "8832 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "cholovYisroel": true
  },
  {
    "name": "Hummus Yummy",
    "type": "RESTAURANT",
    "address": "12510 Burbank Blvd",
    "city": "Valley Village",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "cholovYisroel": true,
    "phone": "818-691-3737"
  },
  {
    "name": "La Brea Bagel Co",
    "type": "CAFE",
    "address": "7308 Beverly Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "cholovYisroel": true,
    "phone": "323-965-1287"
  },
  {
    "name": "Madela Pizza",
    "type": "RESTAURANT",
    "address": "7565 Beverly Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "cholovYisroel": true
  },
  {
    "name": "Pizza Mark",
    "type": "RESTAURANT",
    "address": "1708 S Robertson Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "cholovYisroel": true,
    "phone": "424-523-3131"
  },
  {
    "name": "Popular Encino",
    "type": "RESTAURANT",
    "address": "18047 Ventura Blvd",
    "city": "Encino",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "cholovYisroel": true,
    "phone": "818-796-2276"
  },
  {
    "name": "Shalom Pizza",
    "type": "RESTAURANT",
    "address": "8715 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "cholovYisroel": true,
    "phone": "310-271-2255"
  },
  {
    "name": "The Milky Way",
    "type": "RESTAURANT",
    "address": "9108 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "cholovYisroel": true,
    "phone": "310-859-0004"
  },
  {
    "name": "Trattoria Natalie",
    "type": "RESTAURANT",
    "address": "8681 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "cholovYisroel": true,
    "phone": "310-246-1826"
  },
  {
    "name": "Unique Caf\u00e9",
    "type": "CAFE",
    "address": "18385 Ventura Blvd",
    "city": "Tarzana",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "cholovYisroel": true,
    "phone": "818-757-3100"
  },
  {
    "name": "Sushiko",
    "type": "RESTAURANT",
    "address": "9340 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "cholovYisroel": true,
    "phone": "310-274-3474"
  },
  {
    "name": "Nataly's Acai",
    "type": "RESTAURANT",
    "address": "12341 Burbank Blvd",
    "city": "Valley Village",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "cholovYisroel": true
  },
  {
    "name": "Jeff's Gourmet Sausage Factory",
    "type": "RESTAURANT",
    "address": "8930 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "O/K",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-858-8590"
  },
  {
    "name": "Shanghai Diamond Garden",
    "type": "RESTAURANT",
    "address": "9401 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "O/K",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-553-0998"
  },
  {
    "name": "LA Burger Bar",
    "type": "RESTAURANT",
    "address": "8581 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "O/K",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "424-278-1296"
  },
  {
    "name": "Fish Grill Beverly",
    "type": "RESTAURANT",
    "address": "7226 Beverly Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "O/K",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "323-937-7162"
  },
  {
    "name": "Fish Grill Pico",
    "type": "RESTAURANT",
    "address": "9618 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "O/K",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-860-1182"
  },
  {
    "name": "Schnitzly",
    "type": "RESTAURANT",
    "address": "9216 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "O/K",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "424-249-3565"
  },
  {
    "name": "Pico Kosher Deli",
    "type": "RESTAURANT",
    "address": "8826 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "O/K",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-273-9381"
  },
  {
    "name": "Kosher Pizza Station",
    "type": "RESTAURANT",
    "address": "8965 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "O/K",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-276-8708"
  },
  {
    "name": "Bodhi Kosher Thai",
    "type": "RESTAURANT",
    "address": "9198 W Olympic Blvd",
    "city": "Beverly Hills",
    "state": "CA",
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher LA",
    "kosherStatus": true,
    "status": "ACTIVE",
    "bishulYisroel": true
  },
  {
    "name": "Haifa Restaurant",
    "type": "RESTAURANT",
    "address": "8717 W. Pico Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher LA",
    "kosherStatus": true,
    "status": "ACTIVE",
    "bishulYisroel": true
  },
  {
    "name": "Roladin",
    "type": "RESTAURANT",
    "address": "19365 Victory Blvd",
    "city": "Tarzana",
    "state": "CA",
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher LA",
    "kosherStatus": true,
    "status": "ACTIVE",
    "bishulYisroel": true
  },
  {
    "name": "Beck's Cafe Encino",
    "type": "RESTAURANT",
    "address": "16101 Ventura Blvd",
    "city": "Encino",
    "state": "CA",
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher LA",
    "kosherStatus": true,
    "status": "ACTIVE",
    "bishulYisroel": true
  },
  {
    "name": "Long Beach Beer Lab",
    "type": "RESTAURANT",
    "address": "518 W Willow St",
    "city": "Long Beach",
    "state": "CA",
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher LA",
    "kosherStatus": true,
    "status": "ACTIVE",
    "bishulYisroel": true
  },
  {
    "name": "Our Kosher Table UCLA",
    "type": "RESTAURANT",
    "address": "574 Hilgard Ave",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher LA",
    "kosherStatus": true,
    "status": "ACTIVE",
    "bishulYisroel": true
  },
  {
    "name": "Bruster's Ice Cream",
    "type": "RESTAURANT",
    "address": "1258 S LA Brea Ave",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher LA",
    "kosherStatus": true,
    "status": "ACTIVE",
    "bishulYisroel": true
  },
  {
    "name": "Photo Kosh",
    "type": "PHOTOGRAPHER",
    "address": "Los Angeles",
    "city": "Los Angeles",
    "state": "CA",
    "kosherStatus": false,
    "kosherCertifier": "NONE",
    "kosherCertifierName": null,
    "status": "ACTIVE",
    "rating": 5.0,
    "priceRange": "$$$"
  },
  {
    "name": "Challah Photo",
    "type": "PHOTOGRAPHER",
    "address": "Los Angeles",
    "city": "Los Angeles",
    "state": "CA",
    "kosherStatus": false,
    "kosherCertifier": "NONE",
    "kosherCertifierName": null,
    "status": "ACTIVE",
    "rating": 5.0,
    "priceRange": "$$$"
  },
  {
    "name": "Tisha Photo",
    "type": "PHOTOGRAPHER",
    "address": "Los Angeles",
    "city": "Los Angeles",
    "state": "CA",
    "kosherStatus": false,
    "kosherCertifier": "NONE",
    "kosherCertifierName": null,
    "status": "ACTIVE",
    "rating": 5.0,
    "priceRange": "$$$"
  },
  {
    "name": "Light Design Events",
    "type": "DECORATOR",
    "address": "Los Angeles",
    "city": "Los Angeles",
    "state": "CA",
    "kosherStatus": false,
    "kosherCertifier": "NONE",
    "kosherCertifierName": null,
    "status": "ACTIVE",
    "rating": 5.0,
    "priceRange": "$$$"
  },
  {
    "name": "Design Kosh",
    "type": "DECORATOR",
    "address": "Los Angeles",
    "city": "Los Angeles",
    "state": "CA",
    "kosherStatus": false,
    "kosherCertifier": "NONE",
    "kosherCertifierName": null,
    "status": "ACTIVE",
    "rating": 5.0,
    "priceRange": "$$$"
  },
  {
    "name": "Lilah Deco",
    "type": "DECORATOR",
    "address": "Los Angeles",
    "city": "Los Angeles",
    "state": "CA",
    "kosherStatus": false,
    "kosherCertifier": "NONE",
    "kosherCertifierName": null,
    "status": "ACTIVE",
    "rating": 5.0,
    "priceRange": "$$$"
  },
  {
    "name": "Cedars Sinai Kosher Kitchen",
    "type": "OTHER",
    "address": "8700 Beverly Blvd",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "310-423-6522",
    "description": "Hospital kosher kitchen"
  },
  {
    "name": "JFS Hirsh Kosher Kitchen",
    "type": "OTHER",
    "address": "338 N. Fairfax Avenue",
    "city": "Los Angeles",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "description": "Community kosher kitchen"
  },
  {
    "name": "Dovid Oved Retreat Center",
    "type": "VENUE",
    "address": "3500 Seymour Road",
    "city": "Running Springs",
    "state": "CA",
    "kosherCertifier": "RCC",
    "kosherCertifierName": "Rabbinical Council of California",
    "kosherStatus": true,
    "status": "ACTIVE",
    "phone": "909-359-2000"
  },
  {
    "name": "Reserve Cut",
    "type": "RESTAURANT",
    "address": "40 Broad St",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$$$",
    "rating": 4.5,
    "description": "Fine dining kosher steakhouse, French-Asian fusion"
  },
  {
    "name": "Abigael's on Broadway",
    "type": "RESTAURANT",
    "address": "1407 Broadway",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "phone": "212-575-1407",
    "priceRange": "$$$",
    "rating": 4.3
  },
  {
    "name": "Mr. Broadway",
    "type": "RESTAURANT",
    "address": "209 W 38th St",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$",
    "description": "Classic kosher deli, midtown staple"
  },
  {
    "name": "Wolf and Lamb Steakhouse",
    "type": "RESTAURANT",
    "address": "10 E 48th St",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$$$",
    "rating": 4.4,
    "description": "Upscale steakhouse midtown"
  },
  {
    "name": "Talia's Steakhouse",
    "type": "RESTAURANT",
    "address": "668 Amsterdam Ave",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "rating": 4.2,
    "description": "UWS steakhouse, open late Sat night"
  },
  {
    "name": "Wall Street Grill",
    "type": "RESTAURANT",
    "address": "90 Broad St",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "description": "FiDi kosher steakhouse"
  },
  {
    "name": "Eighteen Restaurant",
    "type": "RESTAURANT",
    "address": "240 E 81st St",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "description": "Modern kosher UES"
  },
  {
    "name": "Noi Due Carne",
    "type": "RESTAURANT",
    "address": "143 W 69th St",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "rating": 4.4,
    "description": "Italian meat on UWS"
  },
  {
    "name": "Sen Sakana",
    "type": "RESTAURANT",
    "address": "245 W 38th St",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$$$",
    "rating": 4.6,
    "description": "Nikkei (Japanese-Peruvian) kosher"
  },
  {
    "name": "Kasbah Grill",
    "type": "RESTAURANT",
    "address": "251 W 85th St",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "description": "Steakhouse and grill UWS"
  },
  {
    "name": "Anixi",
    "type": "RESTAURANT",
    "address": "609 Columbus Ave",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "description": "Modern Mediterranean UWS"
  },
  {
    "name": "Eden Wok",
    "type": "RESTAURANT",
    "address": "43 E 34th St",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$",
    "rating": 4.1,
    "description": "Kosher Chinese midtown"
  },
  {
    "name": "Mendy's",
    "type": "RESTAURANT",
    "address": "61 E 34th St",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$",
    "description": "Classic kosher deli midtown"
  },
  {
    "name": "Sushi Fussion",
    "type": "RESTAURANT",
    "address": "465 Amsterdam Ave",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$",
    "rating": 4.2
  },
  {
    "name": "Mocha Burger LaGuardia",
    "type": "RESTAURANT",
    "address": "72 LaGuardia Pl",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$",
    "description": "Grass-fed kosher burgers Greenwich Village"
  },
  {
    "name": "Holy Schnitzel",
    "type": "RESTAURANT",
    "address": "300 E 34th St",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kehilla Kashrus",
    "status": "ACTIVE",
    "priceRange": "$$",
    "description": "Schnitzel and Israeli street food"
  },
  {
    "name": "Rothschild TLV",
    "type": "RESTAURANT",
    "address": "17 John St",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "description": "Israeli fine dining FiDi"
  },
  {
    "name": "Shwarma Shabazi",
    "type": "RESTAURANT",
    "address": "188 Allen St",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$",
    "description": "Yemenite shawarma"
  },
  {
    "name": "Bravo Pizza Midtown",
    "type": "RESTAURANT",
    "address": "378 5th Ave",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Tablet-K",
    "status": "ACTIVE",
    "priceRange": "$",
    "description": "Kosher pizza, open since 1937 tradition"
  },
  {
    "name": "Jerusalem Cafe",
    "type": "RESTAURANT",
    "address": "5 E 37th St",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$",
    "description": "Middle Eastern breakfast-dinner"
  },
  {
    "name": "Hummus Kitchen UWS",
    "type": "RESTAURANT",
    "address": "768 Amsterdam Ave",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$",
    "description": "Hummus and Middle Eastern"
  },
  {
    "name": "Hummus Kitchen UES",
    "type": "RESTAURANT",
    "address": "1613 2nd Ave",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$"
  },
  {
    "name": "Tempura NYC",
    "type": "RESTAURANT",
    "address": "270 W 43rd St",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "description": "Kosher Japanese Theater District"
  },
  {
    "name": "Polanco",
    "type": "RESTAURANT",
    "address": "209 W 38th St 2nd Fl",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "description": "Upscale Mexican kosher"
  },
  {
    "name": "Schnitzi",
    "type": "RESTAURANT",
    "address": "26 W 38th St",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$"
  },
  {
    "name": "Smash House 37th",
    "type": "RESTAURANT",
    "address": "22 W 37th St",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$",
    "description": "Smash burgers kosher"
  },
  {
    "name": "Abaita",
    "type": "RESTAURANT",
    "address": "32 W 22nd St",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "description": "Rustic Italian dairy, wood-fired pizza"
  },
  {
    "name": "Gotta Getta Bagel",
    "type": "CAFE",
    "address": "263 First Ave",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$",
    "rating": 4.4
  },
  {
    "name": "B&H Dairy",
    "type": "RESTAURANT",
    "address": "127 2nd Ave",
    "city": "New York",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$",
    "description": "Historic dairy lunch counter since 1938"
  },
  {
    "name": "Akimori",
    "type": "RESTAURANT",
    "address": "557 Kings Highway",
    "city": "Brooklyn",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "description": "Kosher omakase sushi"
  },
  {
    "name": "Bordeaux Steakhouse",
    "type": "RESTAURANT",
    "address": "1922 Coney Island Ave",
    "city": "Brooklyn",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$$$",
    "rating": 4.5,
    "description": "Upscale steakhouse Midwood"
  },
  {
    "name": "The Loft Steakhouse",
    "type": "RESTAURANT",
    "address": "808 40th St",
    "city": "Brooklyn",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$$$",
    "description": "Fine dining Borough Park"
  },
  {
    "name": "Mike's Bistro",
    "type": "RESTAURANT",
    "address": "622 Cortelyou Rd",
    "city": "Brooklyn",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "rating": 4.6,
    "description": "Modern Israeli fine dining Flatbush"
  },
  {
    "name": "Yakar Steakhouse",
    "type": "RESTAURANT",
    "address": "1304 Ave M",
    "city": "Brooklyn",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$$$",
    "description": "Dry-aged steaks, own aging room"
  },
  {
    "name": "Malka",
    "type": "RESTAURANT",
    "address": "56 Adams St",
    "city": "Brooklyn",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "description": "Eyal Shani's legendary schnitzel, DUMBO"
  },
  {
    "name": "Koma",
    "type": "RESTAURANT",
    "address": "1618 Ave M",
    "city": "Brooklyn",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "description": "Kosher omakase Midwood"
  },
  {
    "name": "Izzy's BBQ",
    "type": "RESTAURANT",
    "address": "397 Troy Ave",
    "city": "Brooklyn",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$",
    "description": "Competition-winning smoked BBQ"
  },
  {
    "name": "Cafe Renaissance",
    "type": "RESTAURANT",
    "address": "802 Kings Highway",
    "city": "Brooklyn",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$",
    "description": "Dairy cafe and pizza Flatbush"
  },
  {
    "name": "Cork n Slice",
    "type": "RESTAURANT",
    "address": "1120 Ave J",
    "city": "Brooklyn",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$",
    "description": "Pizza and wine bar"
  },
  {
    "name": "Olympia Pita",
    "type": "RESTAURANT",
    "address": "1419 Coney Island Ave",
    "city": "Brooklyn",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$",
    "description": "Israeli pita and grill"
  },
  {
    "name": "Mr. Broadway Brooklyn",
    "type": "RESTAURANT",
    "address": "1558 Coney Island Ave",
    "city": "Brooklyn",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$"
  },
  {
    "name": "Glatt A La Carte",
    "type": "RESTAURANT",
    "address": "5123 18th Ave",
    "city": "Brooklyn",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "description": "Borough Park steakhouse"
  },
  {
    "name": "Gottlieb's Restaurant",
    "type": "RESTAURANT",
    "address": "352 Roebling St",
    "city": "Brooklyn",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$",
    "description": "Traditional kosher deli Williamsburg"
  },
  {
    "name": "Pomegranate Supermarket",
    "type": "GROCERY",
    "address": "1507 Coney Island Ave",
    "city": "Brooklyn",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "phone": "718-951-7112",
    "rating": 4.6,
    "reviewCount": 1243
  },
  {
    "name": "Breadberry",
    "type": "GROCERY",
    "address": "2121 Coney Island Ave",
    "city": "Brooklyn",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "rating": 4.4
  },
  {
    "name": "Mocha Burger Flatbush",
    "type": "RESTAURANT",
    "address": "1704 Coney Island Ave",
    "city": "Brooklyn",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$"
  },
  {
    "name": "Bass and Bourbon",
    "type": "RESTAURANT",
    "address": "113 Hamilton Ave",
    "city": "Brooklyn",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "description": "Dairy fish restaurant Carroll Gardens"
  },
  {
    "name": "Castell's",
    "type": "RESTAURANT",
    "address": "1814 Coney Island Ave",
    "city": "Brooklyn",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "description": "Modern steakhouse Gravesend"
  },
  {
    "name": "Bay Cafe",
    "type": "RESTAURANT",
    "address": "1906 86th St",
    "city": "Brooklyn",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$"
  },
  {
    "name": "Mill Basin Deli",
    "type": "RESTAURANT",
    "address": "5823 Ave T",
    "city": "Brooklyn",
    "state": "NY",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "priceRange": "$$",
    "description": "Classic kosher deli since 1973"
  },
  {
    "name": "Fuego by Mana",
    "type": "RESTAURANT",
    "address": "3861 NE 163rd St",
    "city": "North Miami Beach",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$$$$",
    "rating": 4.6,
    "description": "Upscale steakhouse, aged meats, Latin flavors"
  },
  {
    "name": "The Harbour Grill",
    "type": "RESTAURANT",
    "address": "9415 Harding Ave",
    "city": "Surfside",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$$$$",
    "rating": 4.5,
    "description": "World-renowned glatt kosher steakhouse, dry aged steak, sushi"
  },
  {
    "name": "Neya Restaurant",
    "type": "RESTAURANT",
    "address": "9491 Harding Ave",
    "city": "Surfside",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$$$$",
    "rating": 4.6,
    "description": "Chef-driven Israeli fine dining"
  },
  {
    "name": "Cine Citta Caff\u00e9",
    "type": "RESTAURANT",
    "address": "9544 Harding Ave",
    "city": "Surfside",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$$",
    "rating": 4.3,
    "cholovYisroel": true,
    "description": "Italian dairy, brick-oven pizza"
  },
  {
    "name": "Backyard BBQ and Brew",
    "type": "RESTAURANT",
    "address": "9472 Harding Ave",
    "city": "Surfside",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$$",
    "rating": 4.5,
    "description": "Kosher BBQ and craft beer"
  },
  {
    "name": "26 Sushi and Tapas",
    "type": "RESTAURANT",
    "address": "9487 Harding Ave",
    "city": "Surfside",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "rating": 4.4,
    "description": "Sushi and tapas"
  },
  {
    "name": "Pita Hut Surfside",
    "type": "RESTAURANT",
    "address": "9537 Harding Ave",
    "city": "Surfside",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$",
    "rating": 4.3,
    "description": "Falafel and Israeli street food"
  },
  {
    "name": "Kosh Miami",
    "type": "RESTAURANT",
    "address": "9490 Harding Ave",
    "city": "Surfside",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "description": "Steakhouse, Asian, tapas"
  },
  {
    "name": "Rustiko",
    "type": "RESTAURANT",
    "address": "9461 Harding Ave",
    "city": "Surfside",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "cholovYisroel": true,
    "description": "Dairy Italian artisan bistro"
  },
  {
    "name": "La Vita E Bella",
    "type": "RESTAURANT",
    "address": "9485 Harding Ave",
    "city": "Surfside",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$$",
    "cholovYisroel": true,
    "description": "Italian dairy, pasta and pizza"
  },
  {
    "name": "Kresy Pizza",
    "type": "RESTAURANT",
    "address": "9545 Harding Ave",
    "city": "Surfside",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$",
    "description": "Mediterranean pizza and falafel"
  },
  {
    "name": "Hikari Miami",
    "type": "RESTAURANT",
    "address": "9501 Collins Ave",
    "city": "Surfside",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$$$$",
    "description": "Luxury Japanese tasting menus"
  },
  {
    "name": "Josh's Deli",
    "type": "RESTAURANT",
    "address": "9517 Harding Ave",
    "city": "Surfside",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$$",
    "description": "Modern deli, Shabbat takeaway"
  },
  {
    "name": "La Plage",
    "type": "RESTAURANT",
    "address": "9449 Collins Ave",
    "city": "Surfside",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "description": "French-Mediterranean at Grand Beach Hotel"
  },
  {
    "name": "Meat Bar",
    "type": "RESTAURANT",
    "address": "9440 Harding Ave",
    "city": "Surfside",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "description": "Modern meat restaurant"
  },
  {
    "name": "Nessa",
    "type": "RESTAURANT",
    "address": "9455 Harding Ave",
    "city": "Surfside",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$$",
    "description": "Casual Israeli-Mediterranean"
  },
  {
    "name": "Street Kitchen",
    "type": "RESTAURANT",
    "address": "9434 Harding Ave",
    "city": "Surfside",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$",
    "description": "Street food and shawarma"
  },
  {
    "name": "The Fresh Carrot",
    "type": "RESTAURANT",
    "address": "9467 Harding Ave",
    "city": "Surfside",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$$",
    "description": "Healthy bowls and wraps"
  },
  {
    "name": "Bagel Boss Surfside",
    "type": "BAKERY",
    "address": "9395 Harding Ave",
    "city": "Surfside",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$",
    "description": "Fresh bagels and deli"
  },
  {
    "name": "The Frieze Ice Cream",
    "type": "RESTAURANT",
    "address": "1626 Michigan Ave",
    "city": "Miami Beach",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$",
    "description": "Artisan ice cream"
  },
  {
    "name": "Foozo Artisan Pizza Aventura",
    "type": "RESTAURANT",
    "address": "2520 NE 186th St",
    "city": "Aventura",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$$",
    "cholovYisroel": true,
    "description": "Artisanal pizza"
  },
  {
    "name": "Tends",
    "type": "RESTAURANT",
    "address": "18106 W Dixie Hwy",
    "city": "Aventura",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$",
    "description": "Crispy chicken tenders"
  },
  {
    "name": "The Motek",
    "type": "RESTAURANT",
    "address": "19565 Biscayne Blvd #938",
    "city": "Aventura",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$$",
    "description": "Mediterranean cafe"
  },
  {
    "name": "Miami Beach Chocolates",
    "type": "BAKERY",
    "address": "Miami Beach",
    "city": "Miami Beach",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "cholovYisroel": true,
    "description": "Artisan chocolates, CY options"
  },
  {
    "name": "JZ Steakhouse Aventura",
    "type": "RESTAURANT",
    "address": "19019 Biscayne Blvd",
    "city": "Aventura",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "description": "Steakhouse"
  },
  {
    "name": "La Matera",
    "type": "RESTAURANT",
    "address": "3861 NE 163rd St",
    "city": "North Miami Beach",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$$$$",
    "description": "Argentinian kosher steakhouse"
  },
  {
    "name": "Alma Steakhouse",
    "type": "RESTAURANT",
    "address": "1000 S Federal Hwy",
    "city": "Hallandale Beach",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "description": "Kosher chef steakhouse, bar and events"
  },
  {
    "name": "House of Dog",
    "type": "RESTAURANT",
    "address": "9487 Harding Ave",
    "city": "Surfside",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$",
    "description": "Kosher hot dogs and fast food"
  },
  {
    "name": "Izzy's BBQ Miami",
    "type": "RESTAURANT",
    "address": "9566 Harding Ave",
    "city": "Surfside",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$$",
    "description": "Competition-winning smoked BBQ, Brooklyn import"
  },
  {
    "name": "Rare Steakhouse",
    "type": "RESTAURANT",
    "address": "9500 Harding Ave",
    "city": "Surfside",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$$$$",
    "description": "Premium steakhouse"
  },
  {
    "name": "The Harbour Bistro",
    "type": "RESTAURANT",
    "address": "9415 Harding Ave",
    "city": "Surfside",
    "state": "FL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "Kosher Miami",
    "status": "ACTIVE",
    "priceRange": "$$",
    "description": "Casual counterpart to Harbour Grill"
  },
  {
    "name": "Ken's Diner and Grill",
    "type": "RESTAURANT",
    "address": "3353 W. Dempster",
    "city": "Skokie",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "847-679-2850",
    "priceRange": "$$",
    "rating": 4.5,
    "description": "Iconic kosher diner since 1976. Burgers, steaks, legendary atmosphere."
  },
  {
    "name": "Shallots Bistro",
    "type": "RESTAURANT",
    "address": "7016 Carpenter Rd",
    "city": "Skokie",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "847-677-3463",
    "priceRange": "$$$",
    "description": "Fine dining kosher. Creative upscale dishes."
  },
  {
    "name": "Milt's BBQ for the Perplexed",
    "type": "RESTAURANT",
    "address": "3411 N. Broadway",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "773-661-6384",
    "priceRange": "$$",
    "rating": 4.6,
    "description": "Famous kosher BBQ. Brisket, ribs, and smoked meats."
  },
  {
    "name": "Nuovo Chicago",
    "type": "RESTAURANT",
    "address": "3149 W. Devon Ave",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "773-465-9030",
    "priceRange": "$$",
    "description": "Italian kosher meat restaurant."
  },
  {
    "name": "Great Chicago Food and Beverage",
    "type": "RESTAURANT",
    "address": "3149 W. Devon Ave",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "773-465-9030",
    "priceRange": "$$",
    "description": "Kosher meat restaurant and catering."
  },
  {
    "name": "The Sandwich Club",
    "type": "RESTAURANT",
    "address": "4507 Oakton St",
    "city": "Skokie",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "847-677-6020",
    "priceRange": "$$",
    "description": "Wraps, sandwiches, catering. Yoshon and Pas Yisroel available."
  },
  {
    "name": "Mizrahi Grill Highland Park",
    "type": "RESTAURANT",
    "address": "215 Skokie Valley Rd",
    "city": "Highland Park",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "847-831-1400",
    "priceRange": "$$",
    "description": "Authentic Israeli shawarma, falafel, kebabs."
  },
  {
    "name": "Mizrahi Grill Skokie",
    "type": "RESTAURANT",
    "address": "9149 N. Gross Point Rd",
    "city": "Skokie",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "224-534-7215",
    "priceRange": "$$",
    "description": "Israeli grill, second location."
  },
  {
    "name": "Ta'boun Grill Skokie",
    "type": "RESTAURANT",
    "address": "8808 N. Gross Point Rd",
    "city": "Skokie",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "847-965-1818",
    "priceRange": "$$",
    "description": "Middle Eastern grill. Falafel, shawarma, kubeh.",
    "yoshon": true
  },
  {
    "name": "Ta'boun Grill Chicago",
    "type": "RESTAURANT",
    "address": "6339 N. California",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "773-381-2606",
    "priceRange": "$$",
    "description": "Middle Eastern grill Devon Ave."
  },
  {
    "name": "B'sari",
    "type": "RESTAURANT",
    "address": "3149 W. Devon Ave",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "priceRange": "$$",
    "description": "Meat restaurant on Devon."
  },
  {
    "name": "Evita Argentinian Steakhouse",
    "type": "RESTAURANT",
    "address": "3149 W. Devon Ave",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "description": "Argentinian kosher steakhouse."
  },
  {
    "name": "YOKO",
    "type": "RESTAURANT",
    "address": "4731 W. Main St",
    "city": "Skokie",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "priceRange": "$$$",
    "rating": 4.7,
    "description": "High-end Japanese sushi and entrees."
  },
  {
    "name": "Crunch",
    "type": "RESTAURANT",
    "address": "8170 McCormick Blvd",
    "city": "Skokie",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "847-213-0494",
    "priceRange": "$$",
    "description": "Kosher fast casual."
  },
  {
    "name": "Tacos Gingi",
    "type": "RESTAURANT",
    "address": "3149 W. Devon Ave",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "priceRange": "$$",
    "description": "Kosher tacos and Mexican."
  },
  {
    "name": "Now We're Cookin' Grill",
    "type": "RESTAURANT",
    "address": "3149 W. Devon Ave",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "priceRange": "$$",
    "description": "BBQ beef ribs and skirt steak."
  },
  {
    "name": "Shanghai Kosher",
    "type": "RESTAURANT",
    "address": "3149 W. Devon Ave",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "priceRange": "$$",
    "description": "Kosher Chinese restaurant."
  },
  {
    "name": "Hamachi Sushi Bar",
    "type": "RESTAURANT",
    "address": "2801 W. Howard St",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "773-293-6904",
    "priceRange": "$$",
    "description": "Kosher sushi bar."
  },
  {
    "name": "Chalavi",
    "type": "RESTAURANT",
    "address": "2931 W. Touhy Ave",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "773-338-9640",
    "priceRange": "$$",
    "description": "Dairy restaurant.",
    "cholovYisroel": true
  },
  {
    "name": "Metro Klub",
    "type": "RESTAURANT",
    "address": "733 W. Madison",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "312-602-2104",
    "priceRange": "$$",
    "description": "Loop kosher deli for businessmen."
  },
  {
    "name": "Tel Aviv Kosher Pizza",
    "type": "RESTAURANT",
    "address": "6349 N. California",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "773-764-8877",
    "priceRange": "$",
    "description": "Dairy pizza.",
    "cholovYisroel": true
  },
  {
    "name": "Dunkin Donuts Devon",
    "type": "RESTAURANT",
    "address": "3132 W. Devon",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "773-262-4561",
    "priceRange": "$",
    "description": "cRc certified Dunkin location."
  },
  {
    "name": "Dunkin Donuts Skokie",
    "type": "RESTAURANT",
    "address": "3900 W. Dempster",
    "city": "Skokie",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "847-673-7099",
    "priceRange": "$",
    "description": "cRc certified Dunkin location."
  },
  {
    "name": "Emma's Bagel Cafe",
    "type": "CAFE",
    "address": "9306 Skokie Blvd",
    "city": "Skokie",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "847-673-3030",
    "priceRange": "$",
    "description": "Fresh bagels, sandwiches, coffee. Dairy and pareve."
  },
  {
    "name": "Eve's Garden Cafe",
    "type": "CAFE",
    "address": "4032 Oakton St",
    "city": "Skokie",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "847-674-8008",
    "priceRange": "$$",
    "description": "Dairy cafe, salads, sandwiches.",
    "cholovYisroel": true
  },
  {
    "name": "Slice of Life",
    "type": "RESTAURANT",
    "address": "4120 W. Dempster",
    "city": "Skokie",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "847-674-2021",
    "priceRange": "$$",
    "description": "Dairy pizza and Italian.",
    "cholovYisroel": true
  },
  {
    "name": "Dairy Star Ice Cream",
    "type": "RESTAURANT",
    "address": "3472 W. Devon",
    "city": "Lincolnwood",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "847-679-3472",
    "priceRange": "$",
    "description": "Ice cream parlor.",
    "cholovYisroel": true
  },
  {
    "name": "Chocolate Shoppe Ice Cream",
    "type": "RESTAURANT",
    "address": "4041 W. Dempster St",
    "city": "Skokie",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "847-674-2900",
    "priceRange": "$",
    "description": "Ice cream shop."
  },
  {
    "name": "Sarah's Tent",
    "type": "GROCERY",
    "address": "4020 Oakton St",
    "city": "Skokie",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "847-674-8008",
    "description": "Full-service kosher market, formerly Hungarian Kosher Foods."
  },
  {
    "name": "Romanian Kosher Sausage Co",
    "type": "BUTCHER",
    "address": "7200 N. Clark St",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OU",
    "kosherCertifierName": "Orthodox Union",
    "status": "ACTIVE",
    "description": "Historic kosher sausage and deli meats."
  },
  {
    "name": "Mariano's Kosher Skokie",
    "type": "GROCERY",
    "address": "3358 W. Touhy Ave",
    "city": "Skokie",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "description": "Kosher section in mainstream grocer."
  },
  {
    "name": "Robert's Fish Market",
    "type": "GROCERY",
    "address": "Peterson Ave",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "description": "Kosher fish market."
  },
  {
    "name": "Good Morgan Fish",
    "type": "GROCERY",
    "address": "2948 W. Devon",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "773-764-8115",
    "description": "Kosher fish market."
  },
  {
    "name": "Moshe's New York Kosher",
    "type": "GROCERY",
    "address": "2900 W. Devon",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "773-338-3354",
    "description": "Kosher groceries and deli."
  },
  {
    "name": "Gratzia Bakery",
    "type": "BAKERY",
    "address": "300 Skokie Valley Rd",
    "city": "Highland Park",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "priceRange": "$$",
    "description": "Formerly Tel-Aviv Kosher Bakery. Fresh baked goods."
  },
  {
    "name": "Shalom Kosher Bakery",
    "type": "BAKERY",
    "address": "3149 W. Devon Ave",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "description": "Kosher bakery."
  },
  {
    "name": "Coco Artisan Sweets",
    "type": "BAKERY",
    "address": "3540 W. Devon Ave",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "description": "Artisan kosher sweets and chocolates.",
    "cholovYisroel": true
  },
  {
    "name": "Candy Squared",
    "type": "BAKERY",
    "address": "3364 W. Devon Ave",
    "city": "Lincolnwood",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "847-420-9795",
    "description": "Kosher candy shop."
  },
  {
    "name": "Bites of Pleasure",
    "type": "BAKERY",
    "address": "4006 Main St",
    "city": "Skokie",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "847-366-4657",
    "description": "Kosher baked goods."
  },
  {
    "name": "Zelda's Sweet Shoppe",
    "type": "BAKERY",
    "address": "4113 W. Main",
    "city": "Skokie",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "847-679-0033",
    "description": "Kosher sweets, cakes, and gifts."
  },
  {
    "name": "Danziger Kosher Catering",
    "type": "CATERER",
    "address": "3910 W. Devon",
    "city": "Lincolnwood",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "847-982-1818"
  },
  {
    "name": "Goldman-Segal Kosher Caterer",
    "type": "CATERER",
    "address": "3411 W. Church St",
    "city": "Skokie",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "847-675-4060"
  },
  {
    "name": "Premier Catering Chicago",
    "type": "CATERER",
    "address": "3760 Dempster St",
    "city": "Skokie",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "224-251-7634"
  },
  {
    "name": "Spertus Kosher Catering",
    "type": "CATERER",
    "address": "610 S. Michigan Ave",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "312-322-1718"
  },
  {
    "name": "Starr Kosher Catering",
    "type": "CATERER",
    "address": "6320 N. Lincoln",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "773-465-6247"
  },
  {
    "name": "Shallots Bistro Catering",
    "type": "CATERER",
    "address": "7016 Carpenter Rd",
    "city": "Skokie",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE",
    "phone": "847-677-3463",
    "priceRange": "$$$"
  },
  {
    "name": "Kirshner's Cuisine Catering",
    "type": "CATERER",
    "address": "2939 W. Devon",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE"
  },
  {
    "name": "Kosher Gourmet Catering",
    "type": "CATERER",
    "address": "3552 W. Devon",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE"
  },
  {
    "name": "Michael C's Catering",
    "type": "CATERER",
    "address": "6411 W. Devon",
    "city": "Chicago",
    "state": "IL",
    "kosherStatus": true,
    "kosherCertifier": "OTHER",
    "kosherCertifierName": "cRc (Chicago Rabbinical Council)",
    "status": "ACTIVE"
  }
];

  console.log(`\n📍 Upserting ${listings.length} listings...`);
  let ok = 0;
  for (const l of listings) {
    const s = slug(l.name, l.city);
    try {
      await prisma.listing.upsert({ where: { slug: s }, update: {}, create: { ...l, slug: s, createdById: admin.id } });
      ok++;
    } catch (e: any) {
      if (e.code === "P2002") {
        try { await prisma.listing.upsert({ where: { slug: s + "-2" }, update: {}, create: { ...l, slug: s + "-2", createdById: admin.id } }); ok++; }
        catch { console.error(`  ⚠ Dup: ${l.name}`); }
      } else { console.error(`  ⚠ ${l.name}: ${String(e.message).slice(0,60)}`); }
    }
  }

  // Events
  const events = [
    { title: "Shabbat Dinner at Rachel's", slug: "shabbat-dinner-rachels", description: "Weekly community Shabbat dinner.", status: "PUBLISHED" as const, startDate: new Date("2026-03-20T19:30:00"), city: "Los Angeles", state: "CA", isRecurring: true, rrule: "FREQ=WEEKLY;BYDAY=FR", attendeeCount: 8, isFree: false, price: 36, organizerId: admin.id },
    { title: "Challah Baking Workshop", slug: "challah-workshop", description: "Hands-on challah baking class.", status: "PUBLISHED" as const, startDate: new Date("2026-03-22T14:00:00"), city: "Los Angeles", state: "CA", isRecurring: true, rrule: "FREQ=WEEKLY;BYDAY=SU", attendeeCount: 12, isFree: false, price: 18, organizerId: admin.id },
    { title: "Shavuot Celebration", slug: "shavuot-2026", description: "Torah learning, cheesecake, late-night study.", status: "PUBLISHED" as const, startDate: new Date("2026-06-11T18:00:00"), endDate: new Date("2026-06-13T22:00:00"), city: "Los Angeles", state: "CA", attendeeCount: 120, isFree: true, organizerId: admin.id },
    { title: "Tisha B'Av Program", slug: "tisha-bav-2026", description: "Eicha reading and lectures.", status: "PUBLISHED" as const, startDate: new Date("2026-07-25T20:00:00"), city: "Los Angeles", state: "CA", isFree: true, organizerId: admin.id },
    { title: "Rosh Hashana Services", slug: "rosh-hashana-2026", description: "High Holiday services. Open to all.", status: "PUBLISHED" as const, startDate: new Date("2026-10-02T18:00:00"), city: "Los Angeles", state: "CA", isFree: true, organizerId: admin.id },
    { title: "NYC Shabbat Across UWS", slug: "shabbat-uws-nyc", description: "Coordinated Shabbat dinners across the Upper West Side.", status: "PUBLISHED" as const, startDate: new Date("2026-03-27T18:30:00"), city: "New York", state: "NY", isRecurring: true, rrule: "FREQ=WEEKLY;BYDAY=FR", attendeeCount: 200, isFree: false, price: 25, organizerId: admin.id },
    { title: "Miami Beach Havdalah", slug: "miami-havdalah", description: "Beachfront Havdalah every Saturday night.", status: "PUBLISHED" as const, startDate: new Date("2026-03-21T20:30:00"), city: "Miami Beach", state: "FL", isRecurring: true, rrule: "FREQ=WEEKLY;BYDAY=SA", attendeeCount: 35, isFree: true, organizerId: admin.id },
    { title: "Chicago Devon Ave Shabbat Walk", slug: "chicago-devon-shabbat", description: "Guided community Shabbat walk through Devon Ave kosher corridor.", status: "PUBLISHED" as const, startDate: new Date("2026-04-03T17:00:00"), city: "Chicago", state: "IL", isRecurring: true, rrule: "FREQ=WEEKLY;BYDAY=FR", attendeeCount: 30, isFree: true, organizerId: admin.id },
    { title: "Skokie Community Dinner", slug: "skokie-community-dinner", description: "Monthly community dinner at Shallots Bistro.", status: "PUBLISHED" as const, startDate: new Date("2026-04-15T18:30:00"), city: "Skokie", state: "IL", isRecurring: true, rrule: "FREQ=MONTHLY;BYDAY=3WE", attendeeCount: 50, isFree: false, price: 45, organizerId: admin.id },
    { title: "Surfside Shabbat by the Sea", slug: "surfside-shabbat-sea", description: "Oceanfront Shabbat dinner in Surfside.", status: "PUBLISHED" as const, startDate: new Date("2026-04-10T19:00:00"), city: "Surfside", state: "FL", isRecurring: true, rrule: "FREQ=WEEKLY;BYDAY=FR", attendeeCount: 60, isFree: false, price: 50, organizerId: admin.id },
  ];
  for (const e of events) await prisma.event.upsert({ where: { slug: e.slug }, update: {}, create: e });

  console.log(`\n═══════════════════════════════════════`);
  console.log(`🎉 FULL SEED COMPLETE!`);
  console.log(`   ${cats.length} categories`);
  console.log(`   ${ok} listings`);
  console.log(`   ${events.length} events`);
  console.log(`   1 admin user`);
  console.log(`   📍 Los Angeles, CA: 67`);
  console.log(`   📍 New York, NY: 29`);
  console.log(`   📍 Chicago, IL: 25`);
  console.log(`   📍 Surfside, FL: 22`);
  console.log(`   📍 Brooklyn, NY: 21`);
  console.log(`   📍 Skokie, IL: 19`);
  console.log(`   📍 Tarzana, CA: 10`);
  console.log(`   📍 Encino, CA: 8`);
  console.log(`   📍 Valley Village, CA: 8`);
  console.log(`   📍 Sherman Oaks, CA: 5`);
  console.log(`   📍 North Hollywood, CA: 4`);
  console.log(`   📍 Reseda, CA: 4`);
  console.log(`   📍 Aventura, FL: 4`);
  console.log(`   📍 Woodland Hills, CA: 3`);
  console.log(`   📍 Beverly Hills, CA: 3`);
  console.log(`   📍 Lincolnwood, IL: 3`);
  console.log(`   📍 Van Nuys, CA: 2`);
  console.log(`   📍 North Miami Beach, FL: 2`);
  console.log(`   📍 Miami Beach, FL: 2`);
  console.log(`   📍 Highland Park, IL: 2`);
  console.log(`   📍 Glendale, CA: 1`);
  console.log(`   📍 West Hills, CA: 1`);
  console.log(`   📍 Canoga Park, CA: 1`);
  console.log(`   📍 Studio City, CA: 1`);
  console.log(`   📍 Long Beach, CA: 1`);
  console.log(`   📍 Running Springs, CA: 1`);
  console.log(`   📍 Hallandale Beach, FL: 1`);

  console.log(`═══════════════════════════════════════\n`);
}

main().catch((e) => { console.error("❌", e); process.exit(1); }).finally(() => prisma.$disconnect());
